
// Generated by Cadence Genus(TM) Synthesis Solution 17.22-s017_1
// Generated on: Nov  7 2023 11:45:48 IST (Nov  7 2023 06:15:48 UTC)

// Verification Directory fv/alu 

module alu(A, B, option, alu_out);
  input [3:0] A, B;
  input [2:0] option;
  output [3:0] alu_out;
  wire [3:0] A, B;
  wire [2:0] option;
  wire [3:0] alu_out;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_28, n_29, n_31, n_32, n_33;
  wire n_34, n_35, n_36, n_37, n_38, n_39;
  aor311d1 g992__8780(.A (n_38), .B (n_10), .C1 (n_39), .C2 (B[3]), .C3
       (A[3]), .Z (alu_out[3]));
  aor311d1 g994__4296(.A (n_37), .B (n_18), .C1 (n_39), .C2 (A[2]), .C3
       (B[2]), .Z (alu_out[2]));
  oai22d1 g993__3772(.A1 (n_34), .A2 (n_36), .B1 (n_35), .B2 (B[3]),
       .ZN (n_38));
  oai22d1 g995__1474(.A1 (n_31), .A2 (n_36), .B1 (n_35), .B2 (B[2]),
       .ZN (n_37));
  aoim22d1 g996__4547(.A1 (n_33), .A2 (n_32), .B1 (n_33), .B2 (n_32),
       .Z (n_34));
  inv0d0 g997(.I (n_29), .ZN (n_31));
  aor311d1 g999__9682(.A (n_28), .B (n_15), .C1 (n_39), .C2 (A[1]), .C3
       (B[1]), .Z (alu_out[1]));
  ad01d1 g998__2683(.A (n_11), .B (A[2]), .CI (n_24), .CO (n_33), .S
       (n_29));
  oai22d1 g1000__1309(.A1 (n_26), .A2 (n_36), .B1 (n_35), .B2 (B[1]),
       .ZN (n_28));
  oai221d1 g1003__6877(.A (n_23), .B1 (n_16), .B2 (A[0]), .C1 (n_35),
       .C2 (B[0]), .ZN (alu_out[0]));
  inv0d0 g1001(.I (n_25), .ZN (n_26));
  ad01d1 g1002__2900(.A (n_13), .B (A[1]), .CI (n_19), .CO (n_24), .S
       (n_25));
  oan211d1 g1004__2391(.A (n_22), .B (B[0]), .C1 (n_20), .C2 (n_9), .ZN
       (n_23));
  oan211d1 g1005__7675(.A (n_2), .B (n_17), .C1 (n_36), .C2 (B[0]), .ZN
       (n_22));
  oaim22d1 g1006__7118(.A1 (n_21), .A2 (A[3]), .B1 (n_21), .B2 (A[3]),
       .ZN (n_32));
  oaim22d1 g1007__8757(.A1 (n_36), .A2 (A[0]), .B1 (n_39), .B2 (A[0]),
       .ZN (n_20));
  mx02d1 g1014__1786(.I0 (n_14), .I1 (A[0]), .S (B[0]), .Z (n_19));
  oai22d1 g1008__5953(.A1 (n_17), .A2 (n_4), .B1 (n_16), .B2 (A[2]),
       .ZN (n_18));
  oai22d1 g1009__5703(.A1 (n_17), .A2 (n_5), .B1 (n_16), .B2 (A[1]),
       .ZN (n_15));
  aoim31d1 g1015__7114(.A (n_14), .B1 (n_7), .B2 (option[2]), .B3
       (option[1]), .ZN (n_36));
  oaim22d1 g1012__5266(.A1 (n_12), .A2 (B[1]), .B1 (n_12), .B2 (B[1]),
       .ZN (n_13));
  oaim22d1 g1011__2250(.A1 (n_12), .A2 (B[2]), .B1 (n_12), .B2 (B[2]),
       .ZN (n_11));
  oai22d1 g1010__6083(.A1 (n_17), .A2 (n_3), .B1 (n_16), .B2 (A[3]),
       .ZN (n_10));
  oaim22d1 g1013__2703(.A1 (n_12), .A2 (B[3]), .B1 (n_12), .B2 (B[3]),
       .ZN (n_21));
  inv0d0 g1016(.I (n_17), .ZN (n_9));
  inv0d0 g1017(.I (n_12), .ZN (n_14));
  nd02d0 g1021__5795(.A1 (n_8), .A2 (option[0]), .ZN (n_16));
  nd02d0 g1018__7344(.A1 (n_8), .A2 (n_7), .ZN (n_17));
  an02d0 g1020__1840(.A1 (n_6), .A2 (option[0]), .Z (n_39));
  nd02d0 g1019__5019(.A1 (n_6), .A2 (n_7), .ZN (n_12));
  nd03d0 g1022__1857(.A1 (option[1]), .A2 (option[2]), .A3 (n_7), .ZN
       (n_35));
  nr02d0 g1024__9906(.A1 (n_1), .A2 (option[1]), .ZN (n_8));
  nr02d0 g1023__8780(.A1 (n_0), .A2 (option[2]), .ZN (n_6));
  nr02d0 g1026__4296(.A1 (A[1]), .A2 (B[1]), .ZN (n_5));
  nr02d0 g1025__3772(.A1 (A[2]), .A2 (B[2]), .ZN (n_4));
  nr02d0 g1027__1474(.A1 (A[3]), .A2 (B[3]), .ZN (n_3));
  inv0d0 g1028(.I (A[0]), .ZN (n_2));
  inv0d0 g1031(.I (option[0]), .ZN (n_7));
  inv0d0 g1029(.I (option[2]), .ZN (n_1));
  inv0d0 g1030(.I (option[1]), .ZN (n_0));

pc3d21 inA0(.PAD(A[0]), .CIN(A1[0]));
pc3d21 inA1(.PAD(A[1]), .CIN(A1[1]));
pc3d21 inA2(.PAD(A[2]), .CIN(A1[2]));
pc3d21 inA3(.PAD(A[3]), .CIN(A1[3]));

pc3d21 inB0(.PAD(B[0]), .CIN(B1[0]));
pc3d21 inB1(.PAD(B[1]), .CIN(B1[1]));
pc3d21 inB2(.PAD(B[2]), .CIN(B1[2]));
pc3d21 inB3(.PAD(B[3]), .CIN(B1[3]));

pc3d21 inOpt0(.PAD(option[0]), .CIN(option1[0]));
pc3d21 inOpt1(.PAD(option[1]), .CIN(option1[0]));
pc3d21 inOpt2(.PAD(option[2]), .CIN(option1[0]));

pc3d21 out0(.PAD(alu_out[0]), .CIN(alu_out1[0]));
pc3d21 out1(.PAD(alu_out[1]), .CIN(alu_out1[1]));
pc3d21 out2(.PAD(alu_out[2]), .CIN(alu_out1[2]));
pc3d21 out3(.PAD(alu_out[3]), .CIN(alu_out1[3]));
endmodule

